### ISSUE TITLE
Unit Testing of new Modifications to FMS

### ISSUE THREAD

**Issue by amberehall** [gaepdit/FMS#294]
```[tasklist]
### Tasks
- [ ] https://github.com/gaepdit/FMS/issues/266
- [ ] https://github.com/gaepdit/FMS/issues/268
- [ ] https://github.com/gaepdit/FMS/issues/274
- [ ] https://github.com/gaepdit/FMS/issues/271
- [ ] https://github.com/gaepdit/FMS/issues/279
```

**Comment by amberehall** [comment]
Complete; Phase 2 migrated to prod
