### ISSUE TITLE
Form Validation

### ISSUE THREAD

**Issue by tom-karasch** [gaepdit/FMS#345]
```[tasklist]
### Tasks
- [ ] #331
- [ ] https://github.com/gaepdit/FMS/issues/346
- [ ] https://github.com/gaepdit/FMS/issues/336
- [ ] https://github.com/gaepdit/FMS/issues/349
- [ ] https://github.com/gaepdit/FMS/issues/351
- [ ] https://github.com/gaepdit/FMS/pull/341
```
